services:
  postgres:
    image: postgres:15
    container_name: my_postgres_reactive
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ${PGDATA_VOLUME}:/var/lib/postgresql/data