spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydb?currentSchema=project_demo_reactive
    username: user
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/mydb?currentSchema=project_demo_reactive
    user: user
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration
    schemas: project_demo_reactive

  datasource:
    driver-class-name: org.postgresql.Driver

  main:
    web-application-type: reactive

server:
  port: 8080

logging:
  level:
    root: INFO

email:
  sender: demo.project@example.com